// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQHYvGm7qv9psYZKHeDcEwRdaA6fsZHg0',
    appId: '1:357762532050:web:c4652eb254053e7147a30b',
    messagingSenderId: '357762532050',
    projectId: 'fintrack-e42f9',
    authDomain: 'fintrack-e42f9.firebaseapp.com',
    storageBucket: 'fintrack-e42f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDTLDMm2_2Wq9eRMrL1bqm3VlWiS7jGaE',
    appId: '1:357762532050:android:386130e4b8c2e36f47a30b',
    messagingSenderId: '357762532050',
    projectId: 'fintrack-e42f9',
    storageBucket: 'fintrack-e42f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0cN-HHXJ1FPcONpu2yh_0ZxvXwLrwx1Q',
    appId: '1:357762532050:ios:6107e23283041f7347a30b',
    messagingSenderId: '357762532050',
    projectId: 'fintrack-e42f9',
    storageBucket: 'fintrack-e42f9.firebasestorage.app',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0cN-HHXJ1FPcONpu2yh_0ZxvXwLrwx1Q',
    appId: '1:357762532050:ios:6107e23283041f7347a30b',
    messagingSenderId: '357762532050',
    projectId: 'fintrack-e42f9',
    storageBucket: 'fintrack-e42f9.firebasestorage.app',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQHYvGm7qv9psYZKHeDcEwRdaA6fsZHg0',
    appId: '1:357762532050:web:0e9328e9aece6f7a47a30b',
    messagingSenderId: '357762532050',
    projectId: 'fintrack-e42f9',
    authDomain: 'fintrack-e42f9.firebaseapp.com',
    storageBucket: 'fintrack-e42f9.firebasestorage.app',
  );
}
